ToDo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todoapp.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todoapp/urls.py
from django.urls import path

from todoapp.views import (index,
                           TaskCreateView,
                           TaskUpdateView,
                           TaskDeleteView,
                           TaskStatusView,
                           TagListView,
                           TagCreateView,
                           TagUpdateView,
                           TagDeleteView)

urlpatterns = [
    path("", index, name="index"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "tasks/<int:pk>/status/",
        TaskStatusView.as_view(),
        name="task-status"
    ),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path(
        "tags/<int:pk>/update/",
        TagUpdateView.as_view(),
        name="tag-update"
    ),
    path(
        "tags/<int:pk>/delete/",
        TagDeleteView.as_view(),
        name="tag-delete"
    ),
]

app_name = "todoapp"

todoapp/models.py
from django.db import models


class Task(models.Model):
    content = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    completed = models.BooleanField(default=False)
    tags = models.ManyToManyField("Tag", blank=True)


class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

todoapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic

from todoapp.models import Task, Tag


def index(request):
    tasks = Task.objects.order_by("completed", "-created")
    context = {"tasks": tasks, "tags": Task.tags}

    return render(request, "todoapp/index.html", context=context)


class TaskCreateView(generic.CreateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todoapp:index")


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todoapp:index")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todoapp:index")


class TagListView(generic.ListView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todoapp:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todoapp:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todoapp:tag-list")


class TaskStatusView(generic.View):
    def get(self, request, pk):
        task = get_object_or_404(Task, pk=pk)
        task.completed = not task.completed
        task.save()

        return HttpResponseRedirect(reverse_lazy("todoapp:index"))

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    {% block title %}
      <title>ToDo List</title>
    {% endblock %}
    <meta name="viewpoint" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
          integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
          crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3">
          {% block sidebar %}
            {% include "includes/sidebar.html" %}
          {% endblock %}
        </div>
        <div class="col-sm-9">
          {% block content %}{% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'todoapp:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todoapp:tag-list' %}">Tags</a></li>
</ul>

templates/todoapp/index.html
{% extends 'base.html' %}

{% block content %}
  <body>
    <h1>TODO list <a class="btn btn-primary float" href="{% url 'todoapp:task-create' %}">Add task</a></h1>

    {% for task in tasks %}
      <h3>{{ task.content }} {% if task.completed %}
        <strong style="color:green">Done</strong>
          <a class="btn btn-secondary float" href="{% url 'todoapp:task-status' pk=task.id %}">Undo</a>
      {% else %}
        <strong style="color:red">Not done</strong>
          <a class="btn btn-success float" href="{% url 'todoapp:task-status' pk=task.id %}">Complete</a>
      {% endif %} </h3>
      Created: {{ task.created }}
      <span style="color: darkred">{% if task.deadline %}Deadline: {{ task.deadline }}{% endif %}</span>
      <br>
      <span style="color: dimgray">
      Tags: {% for tag in task.tags.all %}
        {{ tag }}
      </span>
      {% endfor %}
      <a href="{% url 'todoapp:task-update' pk=task.id %}">Update</a>
      <a href="{% url 'todoapp:task-delete' pk=task.id %}">Delete</a>
    {% endfor %}
    <hr>
  </body>
{% endblock %}

templates/todoapp/tag_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Delete {{ tag }}?</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Yes" class="btn btn-primary">
  </form>
{% endblock %}

templates/todoapp/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todoapp/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Tags list <a href="{% url 'todoapp:tag-create' %}" class="btn btn-primary float">Add</a></h1>


  {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
      {% for tag in tag_list %}
        <tr>
          <td>{{ tag.name }}</td>
          <td><a class="btn btn-secondary" href="{% url 'todoapp:tag-update' pk=tag.id %}">Update</a></td>
          <td><a class="btn btn-secondary" href="{% url 'todoapp:tag-update' pk=tag.id %}">Delete</a></td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>No tags found.</p>
  {% endif %}
{% endblock %}

templates/todoapp/task_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Delete {{ task }}?</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Yes" class="btn btn-primary">
  </form>
{% endblock %}

templates/todoapp/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}